#!/bin/sh

name=
package=
type=
output=

# オプションをハンドリング
while getopts n:p:t:o:s:h opt
do
	case $opt in
	n )    name=$OPTARG
	       ;;
	p )    package=$OPTARG
	       ;;
	t )    type=$OPTARG
	       ;;
	o )    output=$OPTARG
	       ;;
	h )    echo '使用方法: generate [<オプション>] [名前]
バージョン 1.0.5
    	
利用可能なオプション:
    -n クラスの名前
    -p クラスのパッケージ（デフォルトは"application"です。）
    -t クラスのタイプ（"View", "Model", "Thread" を指定することが出来ます。デフォルトは "View"）
    -o 出力先（指定しない場合は、パッケージとタイプから出力先を決めます）
    	
Genius Framework は Flex 用のフレームワークです。
さらに詳しい情報は、http://seagirl.jp/genius/ をご覧ください。'
		   exit
		   ;;
    ? )    echo 'Usage -h'
		   exit
		   ;;
	esac
done

# オプションを全て削除し、引数だけを残す
shift $((OPTIND - 1))

# カレントディレクトリ
current=`pwd`

# アウトプットディレクトリ
output=${current}/${output%*/}/

# スクリプトのあるディレクトリ
path=${0%/*}

if [ ${type:-0} = 0 ]
then
	ant -buildfile ${path}/build.xml genius -Dname=${name} -Dtype=${type}
else
	ant -buildfile ${path}/build.xml genius -Dname=${name}
fi

exit
